config/routes.rb
Rails.application.routes.draw do
  root "fruits#index"
  resources :fruits, only: [:index]
  post '/classify', to: 'fruits#classify'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
    require 'ai4r'
    def index
        # Display a form to input fruit features
    end

    def classify
        # Parse form parameters and create a fruit instance
        fruit = Fruit.new(color: params[:color], size: params[:size], texture: params[:texture])
      
        # Sample dataset for classification
        dataset = [
          Fruit.new(color: "red", size: "small", texture: "smooth", label: "Apple"),
          Fruit.new(color: "yellow", size: "small", texture: "smooth", label: 'Banana'),
          Fruit.new(color: "yellow", size: "large", texture: "rough", label: 'Pineapple')
          # Add more fruits with different features
        ]
        features = dataset.map { |fruit| [fruit.color, fruit.size, fruit.texture] }
        class_labels = dataset.map { |fruit| fruit.label }
      
        # Combine features and labels into a single dataset
        cleaned_dataset = features.zip + class_labels
      
        # Create and build the decision tree
        id3 = Ai4r::Classifiers::ID3.new
        id3.build(cleaned_dataset)
      
        # Make a prediction
        predicted_class = id3.eval([fruit.color, fruit.size, fruit.texture])
      
        # Display the predicted class in the view
        @prediction = predicted_class
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/views/fruits/index.html.erb
<div class="form-container">
  <h1>Classify Fruit</h1>
  <%= form_tag classify_path do %>
    <%= label_tag :color, 'Color:' %>
    <%= select_tag :color, options_for_select([['Red', :red], ['Yellow', :yellow], ['Green', :green]]) %><br>

    <%= label_tag :size, 'Size:' %>
    <%= select_tag :size, options_for_select([['Small', :small], ['Medium', :medium], ['Large', :large]]) %><br>

    <%= label_tag :texture, 'Texture:' %>
    <%= select_tag :texture, options_for_select([['Smooth', :smooth], ['Rough', :rough]]) %><br>

    <%= submit_tag 'Classify' %>
  <% end %>

  <% if @prediction %>
    <h2>Predicted Class:</h2>
    <p><%= @prediction %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyAi4r</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>